# Generated by Django 5.2.7 on 2025-11-21 23:35

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_pacientes', '0005_cita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('limpieza', 'En limpieza'), ('bloqueada', 'Bloqueada / No usable')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('departamento', models.CharField(choices=[('Emergencias', 'Emergencias'), ('Hospitalización', 'Hospitalización'), ('Consulta Externa', 'Consulta Externa'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Laboratorio', 'Laboratorio'), ('Farmacia', 'Farmacia'), ('Administración', 'Administración'), ('Quirófano', 'Quirófano'), ('Radiología', 'Radiología'), ('Cardiología', 'Cardiología'), ('UCI', 'UCI (Unidad de Cuidados Intensivos)')], max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(16, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('controlado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='Grupos a los que pertenece el usuario.', related_name='usuarios', to='auth.group', verbose_name='grupos')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_permisos', to='auth.permission', verbose_name='permisos de usuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pacientes.paciente')),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.cama')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('cargo', models.CharField(choices=[('Medico', 'Médico'), ('Enfermero', 'Enfermero'), ('Tecnico', 'Técnico'), ('Administrador', 'Administrador'), ('Recepcionista', 'Recepcionista'), ('Farmaceutico', 'Farmacéutico'), ('Auxiliar', 'Auxiliar')], max_length=50)),
                ('departamento', models.CharField(blank=True, choices=[('Emergencias', 'Emergencias'), ('Hospitalización', 'Hospitalización'), ('Consulta Externa', 'Consulta Externa'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Laboratorio', 'Laboratorio'), ('Farmacia', 'Farmacia'), ('Administración', 'Administración'), ('Quirófano', 'Quirófano'), ('Radiología', 'Radiología'), ('Cardiología', 'Cardiología'), ('UCI', 'UCI (Unidad de Cuidados Intensivos)')], max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones')], default='Activo', max_length=20)),
                ('grupo_cargo', models.CharField(blank=True, choices=[('Grupo 1', 'Grupo 1'), ('Grupo 2', 'Grupo 2'), ('Grupo 3', 'Grupo 3')], max_length=10, null=True)),
                ('horario', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_espera', 'En espera'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada'), ('en_progreso', 'En Progreso')], default='pendiente', max_length=20)),
                ('numero_atencion', models.CharField(blank=True, max_length=20, null=True)),
                ('prioridad', models.IntegerField(default=1)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'cargo': 'Medico'}, on_delete=django.db.models.deletion.CASCADE, to='gestion_administrativa.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='cama',
            name='habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='gestion_administrativa.habitacion'),
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado')], default='Pendiente', max_length=20)),
                ('tecnico_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='gestion_administrativa.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TurnoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='gestion_administrativa.empleado')),
            ],
        ),
    ]
