# Generated by Django 5.2.7 on 2025-11-14 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaAsignacioncama',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_asignacioncama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaCama',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gestion_administrativa_cama',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaCita',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=20)),
                ('paciente', models.CharField(max_length=100)),
                ('numero_atencion', models.CharField(blank=True, max_length=20, null=True)),
                ('prioridad', models.IntegerField()),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_cita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaEmpleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('grupo_cargo', models.CharField(blank=True, max_length=10, null=True)),
                ('horario', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaHabitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('departamento', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.PositiveIntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gestion_administrativa_habitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaHorarioestandar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'gestion_administrativa_horarioestandar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaListaespera',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField()),
            ],
            options={
                'db_table': 'gestion_administrativa_listaespera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaMantenimiento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'gestion_administrativa_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaPaciente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ci', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaRol',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaTurnoempleado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'db_table': 'gestion_administrativa_turnoempleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaUsuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'gestion_administrativa_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaUsuarioGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gestion_administrativa_usuario_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GestionAdministrativaUsuarioUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'gestion_administrativa_usuario_user_permissions',
                'managed': False,
            },
        ),
    ]
