# Generated by Django 5.2.7 on 2025-11-20 02:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_pacientes', '0002_alter_paciente_apellido_materno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField()),
                ('signos_vitales', models.TextField()),
                ('historia_enfermedad_actual', models.TextField()),
                ('antecedentes_patologicos', models.TextField()),
                ('antecedentes_no_patologicos', models.TextField()),
                ('antecedentes_gineco_obstetricos', models.TextField(blank=True, null=True)),
                ('antecedentes_familiares', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='gestion_pacientes.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='Antecedente',
        ),
    ]
