# Generated by Django 5.2.7 on 2025-11-21 00:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aseguradora',
            options={'verbose_name': 'Aseguradora', 'verbose_name_plural': 'Aseguradoras'},
        ),
        migrations.AlterModelOptions(
            name='planseguro',
            options={'verbose_name': 'Plan de Seguro', 'verbose_name_plural': 'Planes de Seguro'},
        ),
        migrations.AlterModelOptions(
            name='reclamacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Reclamación', 'verbose_name_plural': 'Reclamaciones'},
        ),
        migrations.AlterModelOptions(
            name='transaccion',
            options={'ordering': ['-fecha_transaccion']},
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación del Registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cita',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='fecha_transaccion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='fecha_servicio',
            field=models.DateField(verbose_name='Fecha de Servicio'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='monto_aprobado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Aprobado'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='monto_reclamado',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Reclamado'),
        ),
    ]
