# Generated by Django 5.2.7 on 2025-11-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_financiera', '0002_alter_aseguradora_options_alter_planseguro_options_and_more'),
        ('gestion_pacientes', '0005_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='gestion_pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='reclamacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reclamaciones', to='gestion_pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='gestion_pacientes.paciente'),
        ),
    ]
